### ISSUE TITLE
When I have `yield from` in a fixture, a PT004 error is wrongly reported

### ISSUE THREAD

**Issue by cansjt** [m-burst/flake8-pytest-style#127]
# Bug report

## What's wrong

False positive PT004 when fixture use `yield from other_function()`

## How it should work

I guess either flake8-pytest-style is :
- capable of determining that the function called will return a result (and includes a teardown) (recursively)
- or should only emit a warning;

But not report a false positive and exit with an error status.

## System information

* Operating system: 
* Python version: 3.9.5
* flake8 version: 3.9.2
* flake8-pytest-style version: 1.4.2

**Comment by m-burst** [comment]
Hi @cansjt,
Thanks for your report!
I've published v1.4.3 fixing this bug.
