### ISSUE TITLE
Expose py.typed file

### ISSUE THREAD

**Issue by kasium** [m-burst/flake8-pytest-style#153]
Hey,

would you consider to add a py.typed file so that projects using this project in a programmatic way can benefit from the added type hints?
I'm happy to open a PR.

**Comment by m-burst** [comment]
Hi @kasium, I will gladly accept a PR.

Just out of curiosity, what are you trying to accomplish by using the plugin in a programmatic way?

**Comment by kasium** [comment]
Hi, thanks for this. I created the PR.

Reg. your question: I maintain a project (sadly closed source) which acts as a wrapper around several flake8 plugins. Since I love typing, I would like that mypy can consider your type hints.

**Comment by m-burst** [comment]
Hi @kasium,
I have just released v1.6.0 which includes the py.typed file.

**Comment by kasium** [comment]
Thanks a lot!
