### ISSUE TITLE
Inspiration from eslint-plugin-jest

### ISSUE THREAD

**Issue by sobolevn** [m-burst/flake8-pytest-style#16]
Today I thought that `eslint-plugin-jest` can be a great inspiration for this project.
It is a well established project that does the same thing but for `eslint` and `jest` test runner in JavaScript. 

It is possible that they also enforce some best practices that this project does not yet.

https://github.com/jest-community/eslint-plugin-jest

**Comment by m-burst** [comment]
Hi @sobolevn,

Great suggestion! I'll look into it :)

**Comment by m-burst** [comment]
Looked through `eslint-plugin-jest`, `eslint-plugin-mocha` and `eslint-plugin-jasmine`, created a few new rule requests: #28 #29 #30 #31

**Comment by sobolevn** [comment]
@m-burst great job 👍 

Thanks a lot for working on this project!
