### ISSUE TITLE
Allow `assert` in `pytest.raises()` block

### ISSUE THREAD

**Issue by dandreevv** [m-burst/flake8-pytest-style#201]
# Rule request

## Description

Allow assert statement in `pytest.raises()` block. Rule – PT012.
Now it is impossible to check the correctness of the Exception:

**Example**:
```
with pytest.raises(CustomError) as exc_info:
    client.send_sms(sms)

    assert exc_info.value.http_status == expected_status
    assert exc_info.value.description == expected_description
```
**Error**: `PT012 pytest.raises() block should contain a single simple statement`

## Rationale

There is no alternatives to check Exceptions correctness.

**Comment by m-burst** [comment]
Hi @dandreevv,

The exception details should be checked **after** the `pytest.raises()` block, not within it.

The code you provided contains an error: if `client.send_sms(sms)` raises any exception, the `assert` statements will never run, so the test will not check whether the exception fields are correct.
Essentially this is the exact problem that `PT012` is intended to prevent.
