### ISSUE TITLE
When I have dictionaries with different insert order in test, PT014 happens

### ISSUE THREAD

**Issue by abcdenis** [m-burst/flake8-pytest-style#203]
# Bug report

## What's wrong

If dictionary insertion order is valueable, e.g. for testing code stability, plugin fires PT014 warning.

Note: I know that code should be stable and do not use side effect of dictionary insertion order.

Sample:

[test_dict_insert_order_PT014_warning.py.txt](https://github.com/m-burst/flake8-pytest-style/files/10036449/test_dict_insert_order_PT014_warning.py.txt)

## How it should work

I think it could have option to more precise dictionary comparison.

## System information

* Operating system: macos
* Python version: 3.7
* flake8 version: 4.0.1
* flake8-pytest-style version: 1.4.0

**Comment by m-burst** [comment]
Hi @abcdenis,
This looks like a very rare edge case. In my experience there isn't (and shouldn't be) a lot of code relying on the dictionary iteration order, and thus parameters like yours are more likely to be a mistake than to be intended.
I don't think it would be correct to change PT014 to treat such dictionaries as different, and I would suggest to solve this on a case-by-case basis with a `# noqa: PT014`.
If you have a lot of such tests in your codebase, you might disable the rule per-file or globally.
