### ISSUE TITLE
When I have pytest.fail() in a test, it is incorrectly detected as a unittest-style assertion

### ISSUE THREAD

**Issue by mwgamble** [m-burst/flake8-pytest-style#222]
# Bug report

## What's wrong

In the latest version of this plugin (1.7.1 at the time of writing), PT009 incorrectly reports `pytest.fail()` as a unittest-style assertion.

## How it should work

PT009 shouldn't be warning about calling `pytest` functions when it's documented as warning about `unittest` functions. There should be no warnings emitted for code that calls `pytest.fail()`.

## System information

* Operating system: Linux
* Python version: 3.9
* flake8 version: 5.0.4
* flake8-pytest-style version: 1.7.1

**Comment by m-burst** [comment]
Hi @mwgamble, thanks for reporting this!
This was an unfortunate regression introduced in v1.7.1, but it should be fixed now in v1.7.2.
