### ISSUE TITLE
I want a rule that will flag Exception in raises() contexts.

### ISSUE THREAD

**Issue by jenstroeger** [m-burst/flake8-pytest-style#249]
# Rule request

Flag the use of `Exception` for `pytest.raises()` contexts, for example:
```python
with pytest.raises(Exception, match="..."):
    ...
```

## Description

The first argument to `raises()` should be a subclass of `Exception`, and not `Exception` itself — similar to `pylint`s [broad-exception-caught](https://pylint.pycqa.org/en/latest/user_guide/messages/warning/broad-exception-caught.html).

## Rationale

It’ll make tests more specific, just like removing the lint makes error handling more specific and expressive.

**Comment by m-burst** [comment]
Hi @jenstroeger,

I'm not sure I agree with this.
There might be code actually raising `Exception` (which is a bad practice by itself, but out of the scope here), so the tests will also need to catch `Exception`. This can also happen in third-party code, outside of the test author's control.
There already is [PT011](https://github.com/m-burst/flake8-pytest-style/blob/master/README.md) which would force test authors to specify the `match` parameter for the exceptions considered too broad.

**Comment by jenstroeger** [comment]
Thank you @m-burst for your response, but I disagree.

> There might be code actually raising `Exception` […], so the tests will also need to catch `Exception`.

Indeed that is correct, and in that case the flake8 warning should be suppressed with a `# noqa` comment — just like the pylint warning should be suppressed to clarify intent.

> (which is a bad practice by itself, but out of the scope here)

I think it’s quite in scope of flake8 to encourage good coding and testing practices. Not warning at all, I think, continues to encourage bad practices.

Furthermore, by catching & testing for broad `Exception` a test may capture unexpected errors and therefore create a false negative. In fact, I opened this issue because I’ve seen exactly that happening a little too often and I am tired of asking people to _not_ use `Exception`. Help from a tool would drive home the importance of narrowing test cases to only the necessary exceptions.

> There already is [PT011](https://github.com/m-burst/flake8-pytest-style/blob/master/README.md) which […]

That is assuming that people pass a string to an exception, which is not always the case either.
