### ISSUE TITLE
reverse pytest-mark-no-parenthese and pytest-fixture-no-parentheses

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [m-burst/flake8-pytest-style#272]
the general suggestion we use in the pytest docs and in most related projects is dropping the empty parentheses if feasible

**Comment by m-burst** [comment]
Hi @RonnyPfannschmidt,

I understand that the default behaviour of `PT001` and `PT023` goes against the code style shown in pytest docs.
Unfortunately, changing the defaults now would be a breaking change, which I would prefer to avoid.
The behaviour for both rules can be configured in flake8 config.

**Comment by RonnyPfannschmidt** [comment]
from my pov thats a problem

just for my usages i'd have to add that rule to >100 git repos to ensure consistency or avoid the tool

ruff currently mirrors the behaviour but plans to witch around

**Comment by m-burst** [comment]
> i'd have to add that rule to >100 git repos to ensure consistency

May I clarify what you mean by 'adding the rule'?
If you are planning to add the plugin to your dev dependencies, you can [configure](https://github.com/m-burst/flake8-pytest-style#configuration) it at the same time, so it will enforce your preferred code style.

> ruff currently mirrors the behaviour but plans to witch around

Is there a corresponding issue in ruff?

**Comment by RonnyPfannschmidt** [comment]
So far none of the git repos where I intend to add this has a costom flake8 config, I'm relatively strictly against adding one as it's a starting point that allows people inconsistency

There's not yet a issue in ruff do for the actual detail

They plan a larger reorganize off the rules away from replicating other ecosystem plugins and discussions about this issue there indicates that they would also prefer a default rule that's the reverse of the replica of this plugin

**Comment by Mogost** [comment]
I think we need to make this breaking change. The default configuration should promote the best variant.  Also it not a bit breaking change because it's configurable.

**Comment by m-burst** [comment]
I've just released v2.0.0 with this change.
