### ISSUE TITLE
Only enable flake-pytest-style when pytest is in use

### ISSUE THREAD

**Issue by paisleyrob** [m-burst/flake8-pytest-style#273]
# Rule request

Some of our projects use pytest some don't. Our flake8 includes pytest-style suggestions to catch pytest issues. Some of the projects don't use pytest at all and warnings are triggered like the following examples

* `PT009 use a regular assert instead of unittest-style 'assertEqual'`
* `PT027 use pytest.raises() instead of unittest-style 'assertRaises'`

## Description

If `import pytest` hasn't happened, disable pytest-style checks.

## Rationale

Allows the same flake8 CI container to execute against both pytest and unittest projects.

**Comment by m-burst** [comment]
Hi @paisleyrob,

Unfortunately the check based on imports would not be correct, because simple pytest-based tests do not even need to import pytest.
