### ISSUE TITLE
Port flake8-pytest features

### ISSUE THREAD

**Issue by sobolevn** [m-burst/flake8-pytest-style#5]
Currently we use both `flake8-pytest` and `flake8-pytest-style`

I would love to drop `flake8-pytest` dependency, because:
- It fails on windows, see https://github.com/wemake-services/wemake-python-styleguide/issues/337
- There are no issue to report on Github
- This project is not active for the last 3 years

We can port the only violation there is from `flake8-pytest`, its source code is tiny: https://github.com/vikingco/flake8-pytest/blob/master/flake8_pytest.py

And after that there would be no need in this extra dependency. `flake8-pytest-style` would be enough. By the way, thank you for an awesome library!

**Comment by m-burst** [comment]
Hi @sobolevn, I'll look into it

**Comment by m-burst** [comment]
Hi @sobolevn, this is released in v0.2.0.
Please note, however, that this plugin might fail on Windows as well due to afonasev/flake8-plugin-utils#9.

**Comment by sobolevn** [comment]
@m-burst thanks a lot!

Do you want to do the honours and remove `flake8-pytest` from `wemake-python-styleguide`? 
Here's the related issue: https://github.com/wemake-services/wemake-python-styleguide/issues/1221
