### ISSUE TITLE
PT004 fires on abstract fixtures

### ISSUE THREAD

**Issue by apple1417** [m-burst/flake8-pytest-style#87]
# Bug report

## What's wrong

I use the following pattern in a few places, where a base class defines tests, some of which expect fixtures to be defined in child classes.
```py
from abc import ABC, abstractmethod
import pytest


class BaseTest(ABC):
    @pytest.fixture(scope="class")
    @abstractmethod
    def my_value(self):
        raise NotImplementedError

    def test_value_even(self, my_value):
        assert my_value % 2 == 0


class TestImplementation(BaseTest):
    @pytest.fixture(scope="class")
    def my_value(self):
        return 2
```
This leads to the error:
```
test.py:8:5: PT004 fixture 'my_value' does not return anything, add leading underscore
```

There are a few ways to avoid this, but none are totally satisfactory.
 1. Remove the fixture decorator. This would require a comment mentioning that it's supposed to be a fixture, and any special arguments (e.g. scope) to go with it.
 2. Remove the abstract method decorator. This makes you lose the safety it gives, you would be allowed to instantiate classes which don't have it defined.
 3. Return a value in the abstract method. It is still possible to call the implementation of abstract methods, this might cause unexpected behavior. You can return a value after an unconditional `raise NotImplementedError` to avoid this, but that leads to unreachable code errors.
 4. Move the fixture code into `setup_class`. Not all fixtures can be moved, they may depend on other fixtures, and they may return values which can't just be set in a global.
 5. Use a `noqa`. Does this one even need an explanation?

## How it should work

Ideally anything decorated with `abstractmethod` should be ignored for PT004, and possibly also PT005.

## System information
<details>
  <summary>Expand</summary>

```
> flake8 --bug-report
{
  "dependencies": [],
  "platform": {
    "python_implementation": "CPython",
    "python_version": "3.9.0",
    "system": "Windows"
  },
  "plugins": [
    {
      "is_local": false,
      "plugin": "flake8-pytest-style",
      "version": "1.3.0"
    },
    {
      "is_local": false,
      "plugin": "mccabe",
      "version": "0.6.1"
    },
    {
      "is_local": false,
      "plugin": "pycodestyle",
      "version": "2.6.0"
    },
    {
      "is_local": false,
      "plugin": "pyflakes",
      "version": "2.2.0"
    }
  ],
  "version": "3.8.4"
}
```

</details>

**Comment by m-burst** [comment]
Hi @apple1417,
This is fixed in v1.4.0 which I've just released.
